import Nav from "@/components/Nav";
import { logoIcon } from "@/config/assets";
import "@/styles/style.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: logoIcon,
  }
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="fr">
      <body>
        <header>
          <Nav />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
